/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c PowerSaverManagerAdaptor -a powersavermanageradaptor.h:powersavermanageradaptor.cpp powersavermanager.xml -i powersavermanagertypes.h
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef POWERSAVERMANAGERADAPTOR_H
#define POWERSAVERMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "powersavermanagertypes.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.syberos.powersavermanager.Interface
 */
class PowerSaverManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.syberos.powersavermanager.Interface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.syberos.powersavermanager.Interface\">\n"
"    <property access=\"read\" type=\"as\" name=\"users\"/>\n"
"    <signal name=\"powerSavingChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"level\"/>\n"
"    </signal>\n"
"    <method name=\"enablePowerSaving\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"level\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"disablePowerSaving\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"getPowerSavingLevel\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"setPowerSavingStrategy\">\n"
"      <annotation value=\"powerSaverManagerStrategyList\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a(r(sii))\" name=\"strategyList\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"retval\"/>\n"
"    </method>\n"
"    <method name=\"getPowerSavingStrategy\">\n"
"      <annotation value=\"powerSaverManagerStrategyList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a(r(sii))\" name=\"retval\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PowerSaverManagerAdaptor(QObject *parent);
    virtual ~PowerSaverManagerAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QStringList users READ users)
    QStringList users() const;

public Q_SLOTS: // METHODS
    bool disablePowerSaving();
    bool enablePowerSaving(int level);
    int getPowerSavingLevel();
    powerSaverManagerStrategyList getPowerSavingStrategy();
    bool setPowerSavingStrategy(powerSaverManagerStrategyList strategyList);
Q_SIGNALS: // SIGNALS
    void powerSavingChanged(int level);
};

#endif
